### ISSUE TITLE
Ubuntu 16.04 and Anaconda on amd64. ImportError.

### ISSUE THREAD

**Issue by coffeecentric** [scikit-fmm/scikit-fmm#14]
Hi,

Using Ubuntu 16.04 and Anaconda on amd64 I get an ImportError after attempting to run 
python setup.py install
and then (outside the scikit-fmm directory) python -c "import skfmm"

It looks like:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/skfmm/__init__.py", line 51, in <module>
  File "build/bdist.linux-x86_64/egg/skfmm/pfmm.py", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/skfmm/cfmm.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/skfmm/cfmm.py", line 6, in __bootstrap__
ImportError: /home/bl/.cache/Python-Eggs/scikit_fmm-0.0.9-py2.7-linux-x86_64.egg-tmp/skfmm/cfmm.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm

Any help would be greatly appreciated. Thanks very much.

Best wishes,
cc

**Comment by coffeecentric** [comment]
Hi,

Just to try something different, instead of compiling from source, I used 'pip install scikit-fmm'  (again from the anaconda distribution) and got the following ImportError

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bl/anaconda2/lib/python2.7/site-packages/skfmm/__init__.py", line 51, in <module>
    from .pfmm import distance, travel_time, extension_velocities
  File "/home/bl/anaconda2/lib/python2.7/site-packages/skfmm/pfmm.py", line 4, in <module>
    from .cfmm import cFastMarcher
ImportError: /home/bl/anaconda2/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/bl/anaconda2/lib/python2.7/site-packages/skfmm/cfmm.so

I have been able to successfully compile from source and get it to run on my systems python installation. However, I need to use numba and the anaconda distribution for the program I'm working on, so hence my concern. Thanks again.

Best wishes,
cc

**Comment by coffeecentric** [comment]
Ah, well. It seems that I just needed to google a bit more. Sorry about the distraction. The key was to run ' conda install libgcc' to update anaconda's libraries. Thanks very much for skfmm, it's very useful. 

-cc

**Comment by jkfurtney** [comment]
Hi, Thanks for the note about this. I have not seen these errors before so thanks for describing and solving the problem. I have been meaning to make a conda package for scikit-fmm. There was a conda recipe here: https://binstar.org/jmargeta/scikit-fmm but this link is broken now.

**Comment by d-chambers** [comment]
I just ran into the same issue and resolved it in the same way. It may be worth putting something about this in the readme?

**Comment by jkfurtney** [comment]
Thanks for the note and good idea. I added a note in the README. Thanks
