### ISSUE TITLE
Accurate distance without manually setting the dx

### ISSUE THREAD

**Issue by nasseralkmim** [scikit-fmm/scikit-fmm#16]
Hi,

I have an unstructured mesh and I would like to compute the distance from a zero level set for all nodes.

The distances seem to be right only for the 'optimal grid spacing' dx=2/(n-1), so this only works for structured meshes?

Any recommendations?

**Comment by jkfurtney** [comment]
Dear Nasser,

Thanks for the message. The current version of scikit-fmm only supports regular grids.

I am interested in adding an unstructured mesh capability, a few other people have asked about this.

This paper describes the fast marching method adapted to triangular meshes: https://math.berkeley.edu/~sethian/2006/Papers/sethian.kimmel.geodesics.pdf This is also described in James Sethian's book.

We could write this in Python to get it working and convert to c later. The min heap data structure needed for FMM is available in the Python environment.

Could you get this started by posting some sample data? Is your mesh 2d or 3d? Are the elements triangles?

Thanks,
Jason

**Comment by nasseralkmim** [comment]
Hello Jason,

Thanks for answering. I'm solving a simple 2D problem with xFEM (quad elements) and I will probably use your package to define the discontinuity interface.

A simple solution I found was to use a regular grid to define the interface, then use the distance function on this grid with the appropriate dx. Finally, I just interpolate the distance data to the mesh nodes. It seems to work so far. I only need the signed distance function at nodal points.

At this stage, I'm keeping things simple, this does the work for me.

Thanks, great package!

Nasser Alkmim

**Comment by jkfurtney** [comment]
OK sounds good. I will close this issue for now. Thanks, Jason
