### ISSUE TITLE
suggestion: extension to triangle meshes and surfaces

### ISSUE THREAD

**Issue by wmoebius** [scikit-fmm/scikit-fmm#19]
I suggest to extend the module to support triangle meshes and computation on surfaces described by triangle meshes. This would increase applicability of the package. Testing might be realized by scikit-geodesic, http://suttond.github.io/scikit-geodesic/.

**Comment by jkfurtney** [comment]
This paper describes the algorithm: https://math.berkeley.edu/~sethian/2006/Papers/sethian.kimmel.geodesics.pdf

There are some comments on this in issue #16.
