### ISSUE TITLE
suggestion: providing initial condition as function

### ISSUE THREAD

**Issue by wmoebius** [scikit-fmm/scikit-fmm#20]
Providing the phi=0 contour as (x_phi0(s),y_phi0(s)) could be a useful option and avoid back and forth computations on the lattice.

**Comment by jkfurtney** [comment]
Thanks for the note on this, this is a good idea. Here are a few questions:

- Would this only work for closed contours? 
- How would we define the domain of `x_phi0(s)` and `y_phi0(s)`
- Would it be better to define phi as a function of x and y?

The work needed for this is similar to the work I have been doing on the second order initialization branch. https://github.com/scikit-fmm/scikit-fmm/tree/new-init  One of the changes in this branch is a different entry point into the c part of the code which does the FMM. This entry point allows the distance to the initially frozen points to be defined differently (than the current linear reconstruction method).
