### ISSUE TITLE
Vanishing velocity

### ISSUE THREAD

**Issue by sgkang** [scikit-fmm/scikit-fmm#31]
Thanks a lot for making this fast marching code available. 
I am trying to use this code to compute shortest distances in my 3D models, and curious about what is physical meaning of vanishing velocity. Is it some sort of boundary condition (e.g. free surface?)

If I want to know bit more theoretical basis of this code what is a good reference? Also, if I would like to cite this code, what is a good reference?

**Comment by jkfurtney** [comment]
Hi thanks for getting in touch. Can you be more specific about what you mean by vanishing velocity?

The best reference for fast marching methods is "Level Set Methods and Fast Marching Methods 
Evolving Interfaces in Computational Geometry, Fluid Mechanics, Computer Vision, and Materials Science" J.A. Sethian, Cambridge University Press, 1999 Cambridge Monograph on Applied and Computational Mathematics

There is no formal publication about scikit-fmm, if you want to acknowledge it just write that you use the scikit-fmm Python module in you publication.

**Comment by sgkang** [comment]
Hi @jkfurtney thanks for your reply. There were `mask` when setting `phi`, which I thought similar to setting velocity of those masked cell to zero. Could you explain what is happening when these masked cells for `phi`?

**Comment by jkfurtney** [comment]
The input array `phi` can be a masked array. In the masked regions the front is not allowed to propagate. In the `travel_time` function, there is a numerical precision issue for very small values of velocity. So if velocity is less that  numeric_limits<double>::epsilon() (which I think is 2.220446049250313e-16 on most modern machines) the velocity is taken as zero and that region is masked off.

If that is confusing it would be great if you could clarify the documentation and make a pull request.
