### ISSUE TITLE
Fast marching method through diagonal pixels?

### ISSUE THREAD

**Issue by cmarshak** [scikit-fmm/scikit-fmm#32]
I am not sure if this is possible within the confines of the fast marching algorithm but can the existing method be adjusted to move through a diagonal as in the image below where the blue indicates the masked areas (obstacle)?

![image](https://user-images.githubusercontent.com/5975894/68966843-e44c1600-0793-11ea-97fb-148ea52f8e37.png)

The "movement" must occur vertically / horizontally only and requires the channel to be 

![image](https://user-images.githubusercontent.com/5975894/68967036-34c37380-0794-11ea-8c6d-305eccb396e7.png)

Thanks for your help.

**Comment by jkfurtney** [comment]
Hmm, I am not sure what you are asking. I see a purple background with a diagonal yellow band. Which one is the mask? Can you provide some code that demonstrates the problem?

The stencil that this method uses to update each point only looks in the cardinal directions. There are stencils that "look" in the diagonal directions.

**Comment by cmarshak** [comment]
Thank you for your reply. Here are some code snippets. I think a stencil option would probably make this possible.

```
import numpy as np
import numpy.ma as ma
import matplotlib.pyplot as plt
import skfmm

mask_diag = np.diag(np.ones(10))
mask_diag_buff = np.diag(np.ones(10)) + np.diag(np.ones(9), k=1)
init_mask = np.zeros((10, 10))
init_mask[:2, :2] = 1

fig, ax = plt.subplots(1, 3, figsize=(9, 3))
ax[0].imshow(mask_diag)
ax[0].set_title('Diagonal Mask')
ax[1].imshow(mask_diag_buff)
ax[1].set_title('Diagonal Mask with Superdiagonal')
ax[2].imshow(init_mask)
ax[2].set_title('Initialization Mask')
```

![image](https://user-images.githubusercontent.com/5975894/69077927-a47f6b80-09eb-11ea-9760-27551a3cd90a.png)

```

mask_diag = ~(mask_diag.astype(bool))
phi = ma.masked_array(np.ones(mask_diag.shape), mask=mask_diag)
phi.data[init_mask.astype(bool)] = 0
dist = skfmm.distance(phi)

mask_diag = ~(mask_diag_buff.astype(bool))
phi = ma.masked_array(np.ones(mask_diag.shape), mask=mask_diag)
phi.data[init_mask.astype(bool)] = 0
dist_buff = skfmm.distance(phi)

fig, ax = plt.subplots(1, 2, figsize=(8, 4))
ax[0].imshow(dist)
ax[0].set_title('Diagonal Mask')
ax[1].imshow(dist_buff)
ax[1].set_title('Diagonal Mask with Superdiagonal')
```

![image](https://user-images.githubusercontent.com/5975894/69077953-b52fe180-09eb-11ea-99e0-bbd7e3808129.png)

**Comment by jkfurtney** [comment]
Yes, changing the stencil would be the only way to do this as far as I can tell. There is a paper that describes something similar: Multistencils Fast Marching Methods. http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.69.741&rep=rep1&type=pdf

The first- and second-order stencils used by scikit-fmm are baked into the c++ code in a fairly deep way. So adding new stencils would not be easy. I cannot look into this at the moment unfortunately, but I will keep this in mind for future developments.

If you want to experiment with different stencils, you could make a test implementation of FMM in Python. The binary min-heap provided by the module (skfmm.heap) is for just this purpose. Stay in touch if you get something working, it would be a nice feature to add.

**Comment by cmarshak** [comment]
I am preparing a paper using your package and will cite the github repo. I will also reference the paper for future developments that would improve some of the products I am generating and try to look into the heap method - that's awesome that its easy to experiment with from python.

Thank you for your help.

**Comment by jkfurtney** [comment]
I am going to close this issue for now. If anything else come up, let me know.
