### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Sofianel5** [scikit-fmm/scikit-fmm#33]
I've tried in different virtual envs to run skfmm. Each time it says "ImportError: No module named skfmm". I tried doing "pip install scikit-fmm" and it says requirement already satisfied. To make sure it wasn't some weird problem with the python file I did "python -c "import skfmm; skfmm.test(True)"
" in my terminal which gave the output of "ImportError: No module named skfmm" again. 

My python code:
from abc import abstractmethod

import numpy as np
import skfmm
from skimage import measure
from scipy.signal import savgol_filter
from scipy import interpolate

**Comment by jkfurtney** [comment]
I am not sure what the problem is from your description. Maybe you should try installing from source? Are you getting any error messages during the compilation?
