### ISSUE TITLE
Negative Discriminant Error

### ISSUE THREAD

**Issue by aleccarruthers** [scikit-fmm/scikit-fmm#37]
Hello,

I am using the the `travel_time()`  function and receiving a negative discriminant error. I have seen multiple issues regarding this error message, but have not been able to determine a clear method/way to resolve this issue. Is this a known bug and is it being worked on?

Thanks,
Alec

**Comment by dsmccormick8492** [comment]
@aleccarruthers I have had issues with the `travel_time()` function if I used `order=2`. What I did is is wrapped the call in a try-except block: 

```
try:
    # this commonly fails in skfmm due to numerics issues
    travel_times = skfmm.travel_time(phi=grid_masked, speed=grid, order=2) 
except:
    # fall back to order=1
    travel_times = skfmm.travel_time(phi=grid_masked, speed=grid, order=1)
```

Falling back to 'order=1' seems to work in all the cases I was using. I can't speak to how much this affects the numeric accuracy, but it allowed my work to continue.

I hope that helps.
Cheers, David

**Comment by jkfurtney** [comment]
OK, I think this one should be fixed in the current master. I am going to close this one, if this is still a problem, please re-open the issue and give a code sample that shows the problem.
