### ISSUE TITLE
RuntimeError: Negative discriminant in time marcher quadratic.

### ISSUE THREAD

**Issue by HighPerformance01** [scikit-fmm/scikit-fmm#38]
Hi all,

The below simple code generate the below error message (order=2)
RuntimeError: Negative discriminant in time marcher quadratic.

```python
import numpy as np
import skfmm
img=np.zeros((512,512),dtype=np.float64)
seeds=np.ones((512,512),dtype=np.float64)
seeds[254:255,254:255]=0
img=np.random.uniform(low=0,high=1,size=(512,512));
dist1=skfmm.travel_time(seeds,img,order=2);
```
Image has to be highly smoothed in order for the error to disappear or order needs to be 1.

But many times I need order=2 and I can not guarantee a smoothed image.

Would you please help.

Thanks

**Comment by jkfurtney** [comment]
Hi, I just tested this with the latest master and it seems to work. Can you try the latest master branch and give me your feedback. I will get a release out soon. Thanks

**Comment by HighPerformance01** [comment]
Yes, perfect. Hope to see the release soon. 

Thank you
