### ISSUE TITLE
Compute Voronoi?

### ISSUE THREAD

**Issue by okonrad** [scikit-fmm/scikit-fmm#40]
Can the algorithm be used to compute the Voronoi distribution of labels where phi==0?

We'd like to embedded the source code in a C++ class and provide an array where labels are set for all voxels with phi==0. A resulting array should contain the Voronoi distribution of those initial labels.

We managed to encapsulate the code in a C++ class and to use the fmm's interface. So far, we can compute geodesic distance images (we only use the distance_marcher). We also provide a label array from which we compute the phi input image.

Now it is not obvious to us how to 'transport' the labels 'along the shortest distances' through the image. Do you know if this is possible and if so, how?

**Comment by jkfurtney** [comment]
Hi and thanks for the message. What you describe should not be too hard. Have a look at this pull request as it does almost what you want. https://github.com/scikit-fmm/scikit-fmm/pull/30

As far as I understand, when a point is frozen it can look at the adjacent frozen points and carry out either the value at phi=0 or the coordinates of phi=0. I think this is also how 2D image skeletonization works.

**Comment by okonrad** [comment]
Thank you for your fast answer! I also stumbled upon that request and will have a closer look at it now.

Thanks again,
Olaf Konrad

Von: Jason Furtney <notifications@github.com>
Gesendet: Montag, 22. Juni 2020 13:53
An: scikit-fmm/scikit-fmm <scikit-fmm@noreply.github.com>
Cc: Konrad, Olaf <Olaf.Konrad@mevis.de>; Author <author@noreply.github.com>
Betreff: Re: [scikit-fmm/scikit-fmm] Compute Voronoi? (#40)


Hi and thanks for the message. What you describe should not be too hard. Have a look at this pull request as it does almost what you want. #30<https://github.com/scikit-fmm/scikit-fmm/pull/30>

As far as I understand, when a point is frozen it can look at the adjacent frozen points and carry out either the value at phi=0 or the coordinates of phi=0. I think this is also how 2D image skeletonization works.

**Comment by okonrad** [comment]
Well, we made almost the same changes, but were not sure whether those were sufficient, because the result differs quite a lot from the classical Voronoi division computed on base of a Euclidean distance transform. We suspected a bug in our implementation, but maybe the geodesic Voronoi is just different from the Euclidean Voronoi, even in ‘empty space’, i.e., not inside a mask. We need to compute a Voronoi division inside a closed mask, so we expect some differences there.

Thanks again for the prompt answer - and for the wonderful code!

Regards, Olaf Konrad

Von: Jason Furtney <notifications@github.com>
Gesendet: Montag, 22. Juni 2020 13:53
An: scikit-fmm/scikit-fmm <scikit-fmm@noreply.github.com>
Cc: Konrad, Olaf <Olaf.Konrad@mevis.de>; Author <author@noreply.github.com>
Betreff: Re: [scikit-fmm/scikit-fmm] Compute Voronoi? (#40)


Hi and thanks for the message. What you describe should not be too hard. Have a look at this pull request as it does almost what you want. #30<https://github.com/scikit-fmm/scikit-fmm/pull/30>

As far as I understand, when a point is frozen it can look at the adjacent frozen points and carry out either the value at phi=0 or the coordinates of phi=0. I think this is also how 2D image skeletonization works.

**Comment by okonrad** [comment]
Hello,

two things.

Firstly, there is an opportunity for an optimization in the distance_marcher.cpp:

// find and return the correct root
double distanceMarcher::solveQuadratic(int i, const double &a,
                                       const double &b,
                                       double &c)
{
  c-=1;
  //double r0=0;
  //double r1=0;
  double det = pow(b,2)-4*a*c;

  // original

  //if (det>0)
  //{
  //  r0 = (-b+sqrt(det))/2.0/a;
  //  r1 = (-b-sqrt(det))/2.0/a;
  //}
  //else
  //{
  //  return 0;
  //}
  //if (phi_[i] > doubleEpsilon) return r0;
  //else return r1;

  // optimized [OK]

  if (det > 0)
  {
    if (phi_[i] > doubleEpsilon) { return (-b + sqrt(det)) / 2.0 / a; }
    else                         { return (-b - sqrt(det)) / 2.0 / a; }
  }
  else
  {
    return 0;
  }
}

The commented lines is the original, the active code is a bit faster because the square root and two divisions for r0 or r1 are only evaluated if needed.


Secondly, please find attached two screenshots that show the result of a Voronoi computation of two differently labeled voxels that touch each other just diagonally.

The screenshots show a direct volume rendering of just labeled voxels with one value, the other half of the volume is transparent for viewing purposes.

It is clearly visible that the Euclidean Voronoi parts the volume cube diagonally (expected) and the geodesic Voronoi parts the cube ’orthogonally’ (unexpected).

However, the distance values are comparable.

Do you have any idea how to solve this issue? How to make the resulting geodesic Voronoi ‘more diagonal’?


Regards, Olaf Konrad



Von: Jason Furtney <notifications@github.com>
Gesendet: Montag, 22. Juni 2020 13:53
An: scikit-fmm/scikit-fmm <scikit-fmm@noreply.github.com>
Cc: Konrad, Olaf <Olaf.Konrad@mevis.de>; Author <author@noreply.github.com>
Betreff: Re: [scikit-fmm/scikit-fmm] Compute Voronoi? (#40)


Hi and thanks for the message. What you describe should not be too hard. Have a look at this pull request as it does almost what you want. #30<https://github.com/scikit-fmm/scikit-fmm/pull/30>

As far as I understand, when a point is frozen it can look at the adjacent frozen points and carry out either the value at phi=0 or the coordinates of phi=0. I think this is also how 2D image skeletonization works.

**Comment by jkfurtney** [comment]
Thanks for the optimization, I will add that. I need to get a release out soon. I do not see any pictures from in the email or in the GH issue. Can you try to send them some other way?

**Comment by jkfurtney** [comment]
If you have a minute could you make a pull request for the root change? I will merge it in and try to get a release out this week.

**Comment by okonrad** [comment]
I will try to do so.

We also have some results on computing of the Voronoi division using the FMM algorithm, I will share them later as an answer to my initial request, so that others may also learn from it.


Regards, Olaf

Von: Jason Furtney <notifications@github.com>
Gesendet: Dienstag, 23. Juni 2020 16:15
An: scikit-fmm/scikit-fmm <scikit-fmm@noreply.github.com>
Cc: Konrad, Olaf <Olaf.Konrad@mevis.de>; Author <author@noreply.github.com>
Betreff: Re: [scikit-fmm/scikit-fmm] Compute Voronoi? (#40)


If you have a minute could you make a pull request for the root change? I will merge it in and try to get a release out this week.

**Comment by jkfurtney** [comment]
Something to consider in terms of accuracy is that this module has a second-order point update, but the narrow band initialization is only first-order. The first-order error gets marched out, particularly along diagonals. 
We have a (now quite old) branch that uses a higher order narrow band initialization https://github.com/scikit-fmm/scikit-fmm/tree/bicubic-init I need to revisit this branch. You could try this and you may get better results.

**Comment by okonrad** [comment]
Thanks for the hint.

The actual problem is that the algorithm was not designed to keep the 'identity' of the source/emitter voxels; the algorithm was designed to compute an 'anonymous' distance. Furthermore, the algorithm just investigates the orthogonal neighbors of a cell. This results in (some) mislabeling of voxels when the 'voxel front' with different label values meet.

If the source/emitter voxels are fairly far apart, then those mislablings may be tolerable, depending on the use case. But if the source/emitter voxels are close to each other, those mislablings spread over the whole image. Because the algorithm investigates orthogonal neighbors, those artifacts in the voxel fronts lead to orthogonal artifacts in the resulting image.

Unfortunately, the overall accuracy will not change this.

In our application we need a correct labeling of voxels, we have a little computation time to spare, some memory to fill, and we know exactly the set of labels values to be spread. So for each label, we set up a phi image where only those label voxels define the zero contour. Then, we compute the (masked) distance image with your algorithm. When all the distance images are computed, we iterate over all voxels and find the minimum computed distance; we then use the index where we found the minimum distance and map this index back to the label value and write that label value to the output image.

This results in a Voronoi division based on geodesic distances.

And because we don't have _that_ much time to spare, we use OpenMP to let the distance images for each label value be computed in parallel.

---

From left to right: 1. Input source voxels, 2. Result of the augmented FMM, 3. Result of an Euclidean Voronoi algorithm, 4. Result of the min-distance-index-to-label algorithm.

From top to bottom: 1. Emitter voxels fairly far apart, 2. Emitter voxels closer, artifacts appear in the AugFMM, 3. Artifacts in the AugFMM render the result useless.

![labelVoxelsFarApart](https://user-images.githubusercontent.com/67261938/85551661-7ff30e00-b622-11ea-9f95-372e0b590aca.png)

![labelVoxelsCloserTogether](https://user-images.githubusercontent.com/67261938/85551673-82edfe80-b622-11ea-816e-a4d31436c67a.png)

![labelVoxelsAdjacent](https://user-images.githubusercontent.com/67261938/85551682-85e8ef00-b622-11ea-8a32-5debf6fba5c3.png)

**Comment by jkfurtney** [comment]
OK, makes sense, you could also check out multi-stencil fast marching: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.69.741&rep=rep1&type=pdf This may address the diagonal issue. Or simpler you could use a stencil that also has diagonals terms? I have also been thinking about adding this.

**Comment by okonrad** [comment]
Thanks for giving it more thought! Those 'little errors' at the voxel fronts are inherit in those FM methods and they will all amplify them when giving enough space/iterations. They are inherit because of the order of evaluation of orthogonal neighbors.

We are fine with computing a distance image for each label and then choosing the minimum distance as this approach directly implements the definition of a Voronoi division.

However, we'd appreciate the FMM being more precise as you described with the initialization of the narrow band also using second-order terms where applicable. This will likely reduce the amount of differences in the interface of Voronoi regions when compared to the result of a classical Euclidean Voronoi division (in open space).

**Comment by okonrad** [comment]
Closing the issue because we found a stable way to compute a geodesic Voronoi division using the FMM.
