### ISSUE TITLE
Memory leak in extension_velocities

### ISSUE THREAD

**Issue by murraycutforth** [scikit-fmm/scikit-fmm#42]
Hi,

Thanks for a really useful library first of all! I'm using scikit-fmm in a medical imaging application, and I appear to have found a memory leak in `extension_velocities`. Because I'm working with 512^3 volumes, the amount of memory being consumed quickly becomes problematic.

Here's a trace of the memory usage of my code, running `extension_velocities` on 3 different volumes.

![image](https://user-images.githubusercontent.com/11088372/93751236-ab22d480-fbf4-11ea-96f2-cca6c64c581e.png)

I convinced myself that the leak was occurring somewhere specifically in the `extension_velocities` function by running the exact same thing, but calling `skfmm.distance` instead, and seeing that the memory usage stays constant in that case.

After a fair amount of digging in the source code and Python C API documentation, I think I've fixed the issue, although I've never looked into the C API of Python before so I might have misunderstood something. In `fmm.cpp`, where the interface between Python and C++ is defined, there is a special case used to return the results of the extension velocity function:

https://github.com/scikit-fmm/scikit-fmm/blob/ff8a4673b0b1ead9a725762eed99bb45c0e50ec4/skfmm/fmm.cpp#L345-L348

From the documentation on this function (https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue) with format string "OO" the reference count of the objects are incremented. I think this must prevent the reference counts from ever reaching zero when they eventually go out of scope. Replacing the format string with "NN", which is identical except for the reference count not being incremented, gives the following memory profile:

![image](https://user-images.githubusercontent.com/11088372/93757526-d3173580-fbfe-11ea-8e11-2bb5e984084e.png)

If this sounds correct, I can submit a PR with this fix from my fork, or if it's easier one of the maintainers can implement it since it's just a single line change.

**Comment by jkfurtney** [comment]
Hi, thanks for getting in touch and for your effort in tracking down this issue. This confirms what was reported here: https://github.com/scikit-fmm/scikit-fmm/pull/30 Could create a pull request with just the memory leak fix? I am over due to get a release out as there have been several other fixes. Thanks again, Jason

**Comment by murraycutforth** [comment]
Hi @jkfurtney, no problem. I've just submitted the PR.
