### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by lukaszmoroz** [scikit-fmm/scikit-fmm#48]
Could you release a new version on pypi?
I'm getting errors similar to https://github.com/scikit-fmm/scikit-fmm/issues/38 and I see it's been already fixed on master, but the latest release is from two years ago (2019.1.30).

**Comment by jkfurtney** [comment]
Hi, Thanks for the message, I just put out a new release, can you give it a try? Thanks, Jason

**Comment by mrava87** [comment]
Hi, 
I just run a CI of my project and got an error about scikit-fmm https://travis-ci.com/github/mrava87/pylops/builds/213821945 

I guess it is still broken :(

**Comment by jkfurtney** [comment]
This is a different issue see #46 should be an easy fix, the Travis build has been broken for a while

**Comment by mrava87** [comment]
Mmh, I run my pipelines at weekend and everything was working fine wrt installing scikit-fmm as part of my dependency in Travis.

**Comment by jkfurtney** [comment]
The previous version on pip was fine. Recently some changes were made that use more advanced c++ stuff that is causing the problem.

**Comment by mrava87** [comment]
Ook no worries. Happy to wait until you can get a new version on pip that works :)

**Comment by jkfurtney** [comment]
OK, it is fixed in master now. I will push out an update on PyPI tomorrow.

**Comment by mrava87** [comment]
Fantastic :)

**Comment by jkfurtney** [comment]
OK this is done. Let me know if there is still a problem.

**Comment by mrava87** [comment]
Works indeed, brilliant!
