### ISSUE TITLE
Numpy should be a build-system requirement

### ISSUE THREAD

**Issue by davidparsson** [scikit-fmm/scikit-fmm#49]
As stated in https://github.com/scikit-fmm/scikit-fmm/issues/23#issuecomment-742513457, building a wheel during installation of scikit-fmm fails if numpy is not already installed. If so pip will fallback to using the legacy `setup.py install` method, and as of pip 21.0 which was released about a week ago, this is deprecated.

Scipy has recently solved this problem by specifying numpy as a build-system dependency in a `pyproject.toml` file: https://github.com/scipy/scipy/blob/master/pyproject.toml

I'm on Python 3.7.9 and pip 20.3.1 on MacOS 11, and for me this can be reproduced easily on a fresh Python installation/virtualenv:

```
$ pip install wheel
$ pip install scikit-fmm numpy
```

The installation will then continue successfully, but with this deprecation warning:

>   DEPRECATION: scikit-fmm was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.

**Comment by jkfurtney** [comment]
Thanks for the message. So, do we just need to add a `pyproject.toml` file? How does this look? Is there a way to test this without pushing out a new pip release?
 
```
[build-system]
requires = [
    "wheel",
    "setuptools",
    "numpy >= 1.0.2",
]
```

**Comment by davidparsson** [comment]
That looks reasonable to me. I think a fresh virtualenv and `pip install -e /path/to/scikit-fmm-source` would allow testing it without releasing a new version. Let me know if you need help with that.

**Comment by davidparsson** [comment]
Maybe the `-e` flag isn't even needed.

**Comment by jkfurtney** [comment]
Oops I accidently hit close issue, I will reopen it. 

Thanks for the quick reply. I just pushed that file up to the master branch. Could you test it? If it is working, I will get a PyPI release out and close the issue.

**Comment by davidparsson** [comment]
It works like a charm! 🎈 

Thanks for a really quick resolution!

**Comment by davidparsson** [comment]
Will you let me know here once the release is out? Thanks!

**Comment by jkfurtney** [comment]
OK, I just pushed out a release, can you give it a test and reopen the issue if there is a problem. Thanks again

**Comment by davidparsson** [comment]
Installing from PyPI worked fine as well. Thanks a lot!

**Comment by davidparsson** [comment]
I'm a bit confused now, because I remember seeing that this worked, but I must have done something wrong because now I'm having the same issues again with 2021.2.2 when installing from PyPI. However, when installing from GitHub it works fine.

The `pyproject.toml` is **not** included in the [`.tar.gz` uploaded to PyPI](https://pypi.org/project/scikit-fmm/#files), and I am guessing that this is the cause of this.

@jkfurtney, would you mind pushing a new release with this file included? It would be much appreciated!
