### ISSUE TITLE
conda version not consistent

### ISSUE THREAD

**Issue by wmoebius** [scikit-fmm/scikit-fmm#50]
Hi,

Thanks for the new release.

I assume the conda version is automatically created? While https://anaconda.org/conda-forge/scikit-fmm says 2021.1.21 is available, following the instructions installs 2019.1.30.

Thanks!

**Comment by jkfurtney** [comment]
I am not in control of what happens with the conda releases. I am going to close this issue for now since there is nothing I can do. Please post something if you have more information.

**Comment by wmoebius** [comment]
I cannot reproduce this with 2021.2.2, might have been a problem with my specific environments. Seems good now.

A related question is answered here: https://github.com/conda-forge/scikit-fmm-feedstock/issues/11
