### ISSUE TITLE
Visualize shortest path

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [scikit-fmm/scikit-fmm#54]
Hi, thanks for the great code base!

I can get an approximate distance between two points but is a way to extract (and visualize) the shortest path between a 'source' (value of  1) and 'target' (value of -1) using scikit-fmm?

**Comment by wmoebius** [comment]
It's not part of the code yet.

You can find the shortest path using steepest descent going backwards from the target towards the source. Some code snippets are here: https://github.com/wmoebius/OptPath

**Comment by kevin-thankyou-lin** [comment]
Oh perfect, thank you @wmoebius!
