### ISSUE TITLE
cannot import skfmm due to arm64 incompatibility?

### ISSUE THREAD

**Issue by eyhl** [scikit-fmm/scikit-fmm#74]
Hello, thanks for the work. I get the following error when I try to use skfmm inside this other package call scikit-traveltim. It owrked a year ago on the same computer. Any idea how to resolve it?
![problem](https://user-images.githubusercontent.com/40029483/221897456-9ce70f01-56e5-4f9a-b205-1a503fb536d3.png)

**Comment by jkfurtney** [comment]
Part of scikit-fmm is written in C++, in this case it looks like the C++ part did not get built correctly for the new Apple computers, it is trying to load an x84_64 intel binary. I do not have a Mac and I am not sure how the build works on Mac. The best bet would be to try to compile the module from source on your system. Sorry I cannot be more help.
