### ISSUE TITLE
Installation went well, but unable to import 

### ISSUE THREAD

**Issue by himansh78** [scikit-fmm/scikit-fmm#76]
Hi, I installed scikit-fmm and it went well. But when I try to import it shows error regarding numpy version. But my numpy version is 1.22.4, which seems to be well above required (as mentioned in the instructions).
 could you please help-

`import skfmm`
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-fe63e6154ff6> in <module>
----> 1 import skfmm

~\Anaconda3\lib\site-packages\skfmm\__init__.py in <module>
     49 __docformat__ = 'restructuredtext'
     50 
---> 51 from .pfmm import distance, travel_time, extension_velocities
     52 from .heap import heap
     53 

~\Anaconda3\lib\site-packages\skfmm\pfmm.py in <module>
      2 import numpy as np
      3 
----> 4 from .cfmm import cFastMarcher
      5 
      6 FAR, NARROW, FROZEN, MASK = 0, 1, 2, 3

ImportError: numpy.core.multiarray failed to import
`

**Comment by jkfurtney** [comment]
Hi, I think this is related to #75 and is the result of this package not working in Python 3.11. The hold up seems to be the min heap wrapper that is written in Cython. I will get to this as soon as I can. I do not currently have a 3.11 environment to test on. If someone can help with this I would really appreciate it.

**Comment by jkfurtney** [comment]
OK, the 3.11 build should be working now.
