### ISSUE TITLE
Marching issue in a skeleton

### ISSUE THREAD

**Issue by Hanx-Zhang** [scikit-fmm/scikit-fmm#77]
If input array phi is a skeleton where some adjacent pixels are not 4 neighbourhood (they are 8 neighbourhood), fmm method may stop marching. How to deal with this problem?

**Comment by jkfurtney** [comment]
Hello and thanks for getting in touch. Can you provide some example code that illustrates the problem?

**Comment by jkfurtney** [comment]
I will close this for now. If you can provide some more information and reopen the issue, I will have a look.
