### ISSUE TITLE
Inaccurate travel paths

### ISSUE THREAD

**Issue by ncvangilse** [scikit-fmm/scikit-fmm#80]
I am using skfmm to simulate ray paths of seismic waves from a single source.

I had implemented my own version of a function that could back trace the traveltime gradients, but discovered some inaccuracies in the traveltimes. In search for an answer I also found the optimal_path_2d() function in the [wiki in here](https://github.com/scikit-fmm/scikit-fmm/wiki/optimal_path). However, there are also issues with the raypaths from this method.

I have a minimal example that builds a homogenous subsurface and places a source in the upper right corner.
I calculate traveltimes and plot the traced rays (red lines).

I would expect the paths to be linear from any starting point to the source, so I plot these straight rays too (black lines).

However with both my get_raypath_from_starting_points() and the (slightly refactored) optimal_path_2d() I observe discrepancies close to the source.

I will be using this for bayesian inversion, so even small inaccuracies might cause problems.

Ideally I would like to have a point source instead of a zero-contour around the source cell - is that the cause of the problem?

My own:
![my_own](https://github.com/scikit-fmm/scikit-fmm/assets/29121417/6625543f-cced-4c8b-8cc1-270119f04ab2)

My own zoomed:
![my_own_zoomed](https://github.com/scikit-fmm/scikit-fmm/assets/29121417/d239e9d1-c73f-4292-a8cc-0228fe31561c)

Runge kutta (optimal_path_2d):
![runge_kutta](https://github.com/scikit-fmm/scikit-fmm/assets/29121417/3793e2ec-662c-4088-95b3-8bcbfe93f89c)

Runge kutta (optimal_path_2d) zoomed:
![runge_kutta_zoomed](https://github.com/scikit-fmm/scikit-fmm/assets/29121417/9403798f-ebc1-4f58-add3-f1460f9a7a5b)

```
import math
from typing import List

import numpy as np
import skfmm
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColorBar, LinearColorMapper
from scipy.interpolate import RectBivariateSpline


def get_raypath_from_starting_points(x_coords, y_coords, traveltime: np.ndarray,
                                    starting_points: np.ndarray,
                                    step_size:float) -> List[np.ndarray]:
    grad_y, grad_x = np.gradient(traveltime)

    # Interpolating the traveltime field

    fy = RectBivariateSpline(x_coords, y_coords, grad_y)
    fx = RectBivariateSpline(x_coords, y_coords, grad_x)

    # Function to interpolate traveltime and its gradient
    def interpolated_values(x, y):
        dy = fy(x, y)[0]
        dx = fx(x, y)[0]
        return dy, dx

    raypaths = []

    for x, y in starting_points:
        # Initialize the raypath and current position
        raypath = [(x, y)]

        # Iterate to backtrack the raypath
        while True:

            dist_to_source = math.dist((x, y), (source_xy[0], source_xy[1]))

            dy, dx = interpolated_values(x, y)

            # Normalize the gradient direction
            norm = np.sqrt(dy ** 2 + dx ** 2)

            dy, dx = dy / norm, dx / norm

            # Step in the direction opposite to the gradient
            y -= dy * step_size
            x -= dx * step_size

            if step_size > dist_to_source or abs(x - source_xy[0]) < dx or abs(y - source_xy[1]) < dy:
                # Force the last step to hit the source:
                raypath.append((source_xy[0], source_xy[1]))
                break

            if x >= source_xy[0] or y < 0:
                raypath.append((x, y))
                print(f'Could not trace ray back to source. Out of bounds: {x=}, {y=}')
                break

            # Add the new position to the raypath
            raypath.append((x, y))
        raypaths += [np.array(list(zip(*raypath))).T]

    return raypaths


def optimal_path_2d(x_coords,y_coords,travel_time, starting_points, dx,
                    N=500):
    """
    Find the optimal path from starting_point to the zero contour
    of travel_time. dx is the grid spacing
    Solve the equation x_t = - grad t / | grad t |
    """
    def get_velocity(position):
        """ return normalized velocity at pos """
        x, y = position
        vel = np.array([gradx_interp(y, x)[0][0],
                        grady_interp(y, x)[0][0]])
        return vel / np.linalg.norm(vel)

    def runge_kutta(pos, ds):
        """ Fourth order Runge Kutta point update """
        k1 = ds * get_velocity(pos)
        k2 = ds * get_velocity(pos - k1 / 2.0)
        k3 = ds * get_velocity(pos - k2 / 2.0)
        k4 = ds * get_velocity(pos - k3)
        return pos - (k1 + 2 * k2 + 2 * k3 + k4) / 6.0

    grad_t_y, grad_t_x = np.gradient(travel_time, dx)

    gradx_interp = RectBivariateSpline(x_coords, y_coords, grad_t_x)
    grady_interp = RectBivariateSpline(x_coords, y_coords, grad_t_y)

    raypaths = []

    for x, y in starting_points:
        # Initialize the raypath and current position
        raypath = [(x, y)]

        x,y = runge_kutta((x,y), dx)
        for i in range(N):
            raypath += [(x,y)]
            if x >= source_xy[0] or y < 0:
                print(f'Could not trace ray back to source. Out of bounds: {x=}, {y=}')
                break
            x,y = runge_kutta((x,y), dx)
        raypaths += [np.array(list(zip(*raypath))).T]
    return raypaths

x_size, y_size = 10, 10

nx = 100
ny = 100
dx = x_size / nx
dy = y_size / ny

x_coords = np.linspace(0, x_size, nx)
y_coords = np.linspace(0, y_size, ny)
X,Y = np.meshgrid(x_coords, y_coords)

phi = np.ones_like(X)

# set the source in upper right corner:
source_idx = 0, -1

phi[source_idx] = -1

source_xy = X[source_idx], Y[source_idx]

velocity = np.ones_like(X) * 200

traveltime = skfmm.travel_time(phi, velocity , dx=(1,1))

#Create starting points along the edge of the model
starting_points_x = np.array([0] * 10 + list(np.arange(1, 10)))
starting_points_y = np.array(list(np.arange(1, 11)) + [10] * 9)
starting_points = np.vstack([starting_points_x, starting_points_y]).T


# Either use my own implementation
# raypaths = get_raypath_from_starting_points(x_coords, y_coords, traveltime, starting_points=starting_points, step_size=1.0)

# Or the optimal_path_2d from skfmm wiki:
raypaths = optimal_path_2d(x_coords, y_coords, traveltime, starting_points=starting_points, dx=dx)

def plot(traveltime, raypaths, starting_points, source_xy):
    output_file(r"C:\Temp\deleme.html")
    p = figure()
    p.y_range.flipped = True
    mapper = LinearColorMapper(palette='Viridis256')
    img = p.image(image=[traveltime], x=0, y=0, dw=10, dh=10, color_mapper=mapper)
    color_bar = ColorBar(color_mapper=mapper)

    p.add_layout(color_bar, 'right')

    #Draw straight lines
    for x, y in starting_points:
        p.segment(x0=x, y0=y, x1=source_xy[0], y1=source_xy[1], line_color="black", line_width=1)

    #Draw the traced rays
    for raypath in raypaths:
        p.line(raypath[:,0], raypath[:,1], color='red')
    show(p)


plot(traveltime, raypaths, starting_points, source_xy)

```

**Comment by jkfurtney** [comment]
OK, big picture, I think the problem is that the initial narrow band in initialized with a first-order approximation. These first order errors near the starting point propagate outward despite the main calculation being second-order accurate.

I have a branch that does a higher order narrow band initialization. https://github.com/scikit-fmm/scikit-fmm/tree/new-init This branch is behind some other bug fixes and stuff and could take some work to get current again. I have been meaning to get this into the main branch and release it for years, but have not found the motivation or time. For your application, if the starting point is inside the domain by a few cells in each dimension, it should work. 

Could you try compiling that branch and see if it give a better result? When you specify the initial starting point, use the equation of a cone to define phi so the values around the zero contour are continuous (you could also try that in your current code).

**Comment by ncvangilse** [comment]
Thanks! I tried adding 5 cells padding to the grid and made the phi continuous around the zero contour. This helped a lot:
![image](https://github.com/scikit-fmm/scikit-fmm/assets/29121417/1c9c4f1d-2711-4629-b285-7db910889ac7)

I can implement some cheating to interpolate from somewhere outside the zero contour and into the center of the source.

I would also like to try compiling your branch and see how far that would get me, but unfortunately I don't have the skills or tools to do so... :-/
