### ISSUE TITLE
error: Multiple top-level packages discovered in a flat-layout: ['skfmm', 'profile'].

### ISSUE THREAD

**Issue by Ethan2415** [scikit-fmm/scikit-fmm#83]
when i run pip install scikit-fmm==2019.1.30
it shows error: Multiple top-level packages discovered in a flat-layout: ['skfmm', 'profile'].
what is happening and how to solve this?

**Comment by jkfurtney** [comment]
I have not seen this error message before. This could happen if you ran pip from the scikit-learn source directory? Could you provide more details about the operating system and Python version you are using?

**Comment by Ethan2415** [comment]
yes sure, i try to install it on a Ubuntu 20.04 in a conda environment with python=3.7

**Comment by Ethan2415** [comment]
![image](https://github.com/scikit-fmm/scikit-fmm/assets/78804698/52af46f6-c311-4090-83b5-c9a9d6a644b7)
and this is the information popped out

**Comment by jkfurtney** [comment]
OK, I am not sure what is going on here and I am not sure I can be much help. The version you are building is about 5 years old, so if upgrading is an option that may be the way to go. The profile folder in the repo is not used for anything, it is some old scripts to run profilers when I was looking at improving the speed. You could try just deleting that folder or any references to it in the build scripts?

**Comment by Ethan2415** [comment]
OK,  I tried to install the latest version, and no problem occur.  THANK YOU for your help and reply, it's very nice of you.
